---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - configsyncer.intodevops.com
  resources:
  - configsyncers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configsyncer.intodevops.com
  resources:
  - configsyncers/finalizers
  verbs:
  - update
- apiGroups:
  - configsyncer.intodevops.com
  resources:
  - configsyncers/status
  verbs:
  - get
  - patch
  - update
